language: bash

sudo: required

services:
  - docker

env:
  - MAKE_TASK=build
  - MAKE_TASK=lint

script:
  - make $MAKE_TASK

deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: master
      condition: $MAKE_TASK = build
