FROM alpine:3.8
WORKDIR /bin

RUN apk --no-cache add \
  openssh=7.7_p1-r3 \
  ansible=2.5.5-r0

# hadolint ignore=SC2028,SC1117
RUN echo "echo -e  'y\n'| ssh-keygen -N '' -f /root/.ssh/id_rsa" >> ssh_node.sh
RUN echo "mkdir -p /host/root/.ssh" >> ssh_node.sh
RUN echo "cat /root/.ssh/id_rsa.pub >> /host/root/.ssh/authorized_keys" >> ssh_node.sh
RUN echo "ssh localhost" >> ssh_node.sh
RUN chmod +x ssh_node.sh
