FROM alpine
MAINTAINER Pratik Mallya <mallya@us.ibm.com>
WORKDIR /root

RUN apk update && apk add openssh

CMD mkdir -p /host/root/.ssh && \
    echo -e  'y\n'| ssh-keygen -Nq '' -f /root/.ssh/id_rsa && \
    cat /root/.ssh/id_rsa.pub >> /host/root/.ssh/authorized_keys && \
    ssh localhost
