FROM alpine:3.8
WORKDIR /root

RUN apk --no-cache add \
  curl=7.61.1-r0 

RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
	&& chmod +x kubectl \
	&& mv kubectl /usr/local/bin

ENTRYPOINT ["/usr/local/bin/kubectl"]
