FROM ubuntu:latest
MAINTAINER Pratik Mallya <mallya@us.ibm.com>
WORKDIR /root

RUN apt-get update && apt-get install -y \
	curl \
	vim \
	git \
	gettext

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
