FROM alpine
MAINTAINER Pratik Mallya <mallya@us.ibm.com>
WORKDIR /bin

RUN apk update && apk add \
  openssh \
  ansible

RUN echo "echo -e  'y\n'| ssh-keygen -N '' -f /root/.ssh/id_rsa" >> ssh_node.sh
RUN echo "mkdir -p /host/root/.ssh" >> ssh_node.sh
RUN echo "cat /root/.ssh/id_rsa.pub >> /host/root/.ssh/authorized_keys" >> ssh_node.sh
RUN echo "ssh localhost" >> ssh_node.sh
RUN chmod +x ssh_node.sh
