# Dockerfile to use terraform_landscape https://github.com/coinbase/terraform-landscape
FROM alpine:3.8

# this is required for diffy to work on alpine
RUN apk --no-cache add \
  ruby-bundler \
  diffutils

RUN gem install --no-document --no-ri terraform_landscape
CMD ['landscape']
